/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prototipo;

/**
 *
 * @author Usuario
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ayuda = new javax.swing.JButton();
        Marco = new javax.swing.JLabel();
        LineaDecorativa = new javax.swing.JLabel();
        RecordarDatos = new javax.swing.JCheckBox();
        Password = new javax.swing.JPasswordField();
        Nombre = new javax.swing.JTextField();
        OlvideMiContraseña = new javax.swing.JButton();
        Acceder = new javax.swing.JButton();
        CrearCuenta = new javax.swing.JButton();
        Contraseña = new javax.swing.JLabel();
        NombreEmail = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        ventana = new javax.swing.JLabel();
        logoImagen = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/questions.png"))); // NOI18N
        Ayuda.setContentAreaFilled(false);
        getContentPane().add(Ayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 40, -1));

        Marco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(Marco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 460, 430));

        LineaDecorativa.setBackground(new java.awt.Color(255, 255, 255));
        LineaDecorativa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));
        LineaDecorativa.setOpaque(true);
        getContentPane().add(LineaDecorativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 390, -1));

        RecordarDatos.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        RecordarDatos.setText("Recordar datos");
        RecordarDatos.setContentAreaFilled(false);
        RecordarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecordarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(RecordarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 220, -1));

        Password.setBackground(new java.awt.Color(161, 130, 98));
        Password.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        Password.setOpaque(false);
        Password.setSelectionColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 390, 50));

        Nombre.setBackground(new java.awt.Color(161, 130, 98));
        Nombre.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        Nombre.setOpaque(false);
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 390, 50));

        OlvideMiContraseña.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        OlvideMiContraseña.setText("¿Olvidaste tu Contraseña?");
        OlvideMiContraseña.setContentAreaFilled(false);
        OlvideMiContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OlvideMiContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(OlvideMiContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 220, 30));

        Acceder.setBackground(new java.awt.Color(239, 184, 16));
        Acceder.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Acceder.setText("Acceder");
        Acceder.setBorder(null);
        Acceder.setBorderPainted(false);
        Acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccederActionPerformed(evt);
            }
        });
        getContentPane().add(Acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 290, 50));

        CrearCuenta.setFont(new java.awt.Font("Trebuchet MS", 1, 17)); // NOI18N
        CrearCuenta.setText("Crear Cuenta");
        CrearCuenta.setContentAreaFilled(false);
        CrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(CrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 140, 30));

        Contraseña.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Contraseña.setText("Contraseña");
        getContentPane().add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 190, -1));

        NombreEmail.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        NombreEmail.setText("Nombre/Email");
        getContentPane().add(NombreEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 210, -1));

        Login.setBackground(new java.awt.Color(153, 153, 153));
        Login.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login.setText("LOGIN");
        Login.setOpaque(true);
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 460, 50));

        ventana.setBackground(new java.awt.Color(255, 255, 204));
        ventana.setForeground(new java.awt.Color(204, 204, 204));
        ventana.setOpaque(true);
        getContentPane().add(ventana, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 460, 430));

        logoImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/diseno-de-logo.png"))); // NOI18N
        getContentPane().add(logoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 130, 130));

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lavado-en-seco.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 130, 130));

        fondo.setBackground(new java.awt.Color(0, 102, 102));
        fondo.setOpaque(true);
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 649, 662));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccederActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccederActionPerformed

    private void OlvideMiContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OlvideMiContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OlvideMiContraseñaActionPerformed

    private void CrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearCuentaActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void RecordarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecordarDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecordarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acceder;
    private javax.swing.JButton Ayuda;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JButton CrearCuenta;
    private javax.swing.JLabel LineaDecorativa;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Marco;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel NombreEmail;
    private javax.swing.JButton OlvideMiContraseña;
    private javax.swing.JPasswordField Password;
    private javax.swing.JCheckBox RecordarDatos;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoImagen;
    private javax.swing.JLabel ventana;
    // End of variables declaration//GEN-END:variables
}
