/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prototipo;

/**
 *
 * @author Usuario
 */
public class RecuperarContraseña extends javax.swing.JFrame {

    /**
     * Creates new form RecuperarContraseña
     */
    public RecuperarContraseña() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Marco = new javax.swing.JLabel();
        RecuperarContraseña = new javax.swing.JLabel();
        ContraseñaNueva = new javax.swing.JLabel();
        Correo = new javax.swing.JTextField();
        NewPassword = new javax.swing.JPasswordField();
        Email = new javax.swing.JLabel();
        Codigo = new javax.swing.JLabel();
        CodigoEnviado = new javax.swing.JTextField();
        Recuperar = new javax.swing.JButton();
        EnviarCodigo = new javax.swing.JButton();
        LineaDecorativa2 = new javax.swing.JLabel();
        LineaDecorativa1 = new javax.swing.JLabel();
        LineaDecorativa = new javax.swing.JLabel();
        logoImagen = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        BotonRegresar = new javax.swing.JButton();
        ReenviarCodigo = new javax.swing.JButton();
        fondo2 = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Marco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(Marco, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 460, 480));

        RecuperarContraseña.setBackground(new java.awt.Color(153, 153, 153));
        RecuperarContraseña.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        RecuperarContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecuperarContraseña.setText("RECUPERAR CONTRASEÑA");
        RecuperarContraseña.setOpaque(true);
        getContentPane().add(RecuperarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 460, 50));

        ContraseñaNueva.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        ContraseñaNueva.setText("Contraseña Nueva");
        getContentPane().add(ContraseñaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 170, -1));

        Correo.setBackground(new java.awt.Color(161, 130, 98));
        Correo.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        Correo.setOpaque(false);
        Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoActionPerformed(evt);
            }
        });
        getContentPane().add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 270, 50));

        NewPassword.setBackground(new java.awt.Color(161, 130, 98));
        NewPassword.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        NewPassword.setOpaque(false);
        NewPassword.setSelectionColor(new java.awt.Color(255, 255, 255));
        NewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(NewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 270, 50));

        Email.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Email.setText("Email");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 50, -1));

        Codigo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Codigo.setText("Codigo");
        getContentPane().add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 60, -1));

        CodigoEnviado.setBackground(new java.awt.Color(161, 130, 98));
        CodigoEnviado.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        CodigoEnviado.setOpaque(false);
        CodigoEnviado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoEnviadoActionPerformed(evt);
            }
        });
        getContentPane().add(CodigoEnviado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 270, 50));

        Recuperar.setBackground(new java.awt.Color(239, 184, 16));
        Recuperar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Recuperar.setText("Recuperar");
        Recuperar.setBorder(null);
        Recuperar.setBorderPainted(false);
        Recuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecuperarActionPerformed(evt);
            }
        });
        getContentPane().add(Recuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 120, 50));

        EnviarCodigo.setBackground(new java.awt.Color(239, 184, 16));
        EnviarCodigo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        EnviarCodigo.setText("Enviar Codigo");
        EnviarCodigo.setBorder(null);
        EnviarCodigo.setBorderPainted(false);
        EnviarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(EnviarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 120, 50));

        LineaDecorativa2.setBackground(new java.awt.Color(255, 255, 255));
        LineaDecorativa2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        LineaDecorativa2.setOpaque(true);
        getContentPane().add(LineaDecorativa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 2, 325));

        LineaDecorativa1.setBackground(new java.awt.Color(255, 255, 255));
        LineaDecorativa1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        LineaDecorativa1.setOpaque(true);
        getContentPane().add(LineaDecorativa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 2, 325));

        LineaDecorativa.setBackground(new java.awt.Color(255, 255, 255));
        LineaDecorativa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));
        LineaDecorativa.setOpaque(true);
        getContentPane().add(LineaDecorativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 590, 280, -1));

        logoImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/diseno-de-logo.png"))); // NOI18N
        getContentPane().add(logoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 130, 130));

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lavado-en-seco.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 130, 130));

        BotonRegresar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        BotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arrow.png"))); // NOI18N
        BotonRegresar.setText("Regresar");
        BotonRegresar.setContentAreaFilled(false);
        getContentPane().add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, -1));

        ReenviarCodigo.setBackground(new java.awt.Color(153, 153, 153));
        ReenviarCodigo.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        ReenviarCodigo.setText("Reenviar Codigo");
        ReenviarCodigo.setContentAreaFilled(false);
        getContentPane().add(ReenviarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 600, 180, 30));

        fondo2.setBackground(new java.awt.Color(255, 255, 204));
        fondo2.setForeground(new java.awt.Color(204, 204, 204));
        fondo2.setOpaque(true);
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 460, 480));

        fondo1.setBackground(new java.awt.Color(0, 102, 102));
        fondo1.setOpaque(true);
        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 649, 662));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoActionPerformed

    private void EnviarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnviarCodigoActionPerformed

    private void CodigoEnviadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoEnviadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoEnviadoActionPerformed

    private void RecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecuperarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecuperarActionPerformed

    private void NewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JLabel Codigo;
    private javax.swing.JTextField CodigoEnviado;
    private javax.swing.JLabel ContraseñaNueva;
    private javax.swing.JTextField Correo;
    private javax.swing.JLabel Email;
    private javax.swing.JButton EnviarCodigo;
    private javax.swing.JLabel LineaDecorativa;
    private javax.swing.JLabel LineaDecorativa1;
    private javax.swing.JLabel LineaDecorativa2;
    private javax.swing.JLabel Marco;
    private javax.swing.JPasswordField NewPassword;
    private javax.swing.JButton Recuperar;
    private javax.swing.JLabel RecuperarContraseña;
    private javax.swing.JButton ReenviarCodigo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoImagen;
    // End of variables declaration//GEN-END:variables
}
