/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prototipo;

/**
 *
 * @author Usuario
 */
public class Registrar extends javax.swing.JFrame {

    /**
     * Creates new form Registrar
     */
    public Registrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Marco = new javax.swing.JLabel();
        Registrar = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        NombreRegistrar = new javax.swing.JTextField();
        ContraseñaRegistrar = new javax.swing.JPasswordField();
        Contraseña = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        EmailRegistrar = new javax.swing.JTextField();
        CrearCuenta = new javax.swing.JButton();
        LineaDecorativa = new javax.swing.JLabel();
        ConfirmarEmailRegistrar = new javax.swing.JTextField();
        ConfirmarEmail = new javax.swing.JLabel();
        ConfirmarContraseñaRegistrar = new javax.swing.JPasswordField();
        ConfirmarContraseña = new javax.swing.JLabel();
        ApellidoCrear = new javax.swing.JTextField();
        Apellido = new javax.swing.JLabel();
        logoImagen = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        BotonRegresar = new javax.swing.JButton();
        fondo2 = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Marco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(Marco, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 460, 480));

        Registrar.setBackground(new java.awt.Color(153, 153, 153));
        Registrar.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        Registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Registrar.setText("REGISTRAR");
        Registrar.setOpaque(true);
        getContentPane().add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 460, 50));

        Nombre.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Nombre.setText("Nombre");
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 70, -1));

        NombreRegistrar.setBackground(new java.awt.Color(161, 130, 98));
        NombreRegistrar.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        NombreRegistrar.setOpaque(false);
        NombreRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(NombreRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 190, 50));

        ContraseñaRegistrar.setBackground(new java.awt.Color(161, 130, 98));
        ContraseñaRegistrar.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        ContraseñaRegistrar.setOpaque(false);
        ContraseñaRegistrar.setSelectionColor(new java.awt.Color(255, 255, 255));
        ContraseñaRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(ContraseñaRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 190, 50));

        Contraseña.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Contraseña.setText("Contraseña");
        getContentPane().add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 100, -1));

        Email.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Email.setText("Email");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 50, -1));

        EmailRegistrar.setBackground(new java.awt.Color(161, 130, 98));
        EmailRegistrar.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        EmailRegistrar.setOpaque(false);
        EmailRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(EmailRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 190, 50));

        CrearCuenta.setBackground(new java.awt.Color(239, 184, 16));
        CrearCuenta.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        CrearCuenta.setText("Crear Cuenta");
        CrearCuenta.setBorder(null);
        CrearCuenta.setBorderPainted(false);
        CrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(CrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 290, 60));

        LineaDecorativa.setBackground(new java.awt.Color(255, 255, 255));
        LineaDecorativa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));
        LineaDecorativa.setOpaque(true);
        getContentPane().add(LineaDecorativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 420, -1));

        ConfirmarEmailRegistrar.setBackground(new java.awt.Color(161, 130, 98));
        ConfirmarEmailRegistrar.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        ConfirmarEmailRegistrar.setOpaque(false);
        ConfirmarEmailRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarEmailRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmarEmailRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 190, 50));

        ConfirmarEmail.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        ConfirmarEmail.setText("Confirmar Email");
        getContentPane().add(ConfirmarEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 140, -1));

        ConfirmarContraseñaRegistrar.setBackground(new java.awt.Color(161, 130, 98));
        ConfirmarContraseñaRegistrar.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        ConfirmarContraseñaRegistrar.setOpaque(false);
        ConfirmarContraseñaRegistrar.setSelectionColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(ConfirmarContraseñaRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 190, 50));

        ConfirmarContraseña.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        ConfirmarContraseña.setText("Confirmar Contraseña");
        getContentPane().add(ConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 190, -1));

        ApellidoCrear.setBackground(new java.awt.Color(161, 130, 98));
        ApellidoCrear.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        ApellidoCrear.setOpaque(false);
        ApellidoCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoCrearActionPerformed(evt);
            }
        });
        getContentPane().add(ApellidoCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 190, 50));

        Apellido.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Apellido.setText("Apellido");
        getContentPane().add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 70, -1));

        logoImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/diseno-de-logo.png"))); // NOI18N
        getContentPane().add(logoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 130, 130));

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lavado-en-seco.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 130, 130));

        BotonRegresar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        BotonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arrow.png"))); // NOI18N
        BotonRegresar.setText("Regresar");
        BotonRegresar.setContentAreaFilled(false);
        getContentPane().add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, -1));

        fondo2.setBackground(new java.awt.Color(255, 255, 204));
        fondo2.setForeground(new java.awt.Color(204, 204, 204));
        fondo2.setOpaque(true);
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 460, 480));

        fondo1.setBackground(new java.awt.Color(0, 102, 102));
        fondo1.setOpaque(true);
        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 649, 662));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreRegistrarActionPerformed

    private void EmailRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailRegistrarActionPerformed

    private void CrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearCuentaActionPerformed

    private void ConfirmarEmailRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarEmailRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmarEmailRegistrarActionPerformed

    private void ApellidoCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoCrearActionPerformed

    private void ContraseñaRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JTextField ApellidoCrear;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JLabel ConfirmarContraseña;
    private javax.swing.JPasswordField ConfirmarContraseñaRegistrar;
    private javax.swing.JLabel ConfirmarEmail;
    private javax.swing.JTextField ConfirmarEmailRegistrar;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JPasswordField ContraseñaRegistrar;
    private javax.swing.JButton CrearCuenta;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailRegistrar;
    private javax.swing.JLabel LineaDecorativa;
    private javax.swing.JLabel Marco;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField NombreRegistrar;
    private javax.swing.JLabel Registrar;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoImagen;
    // End of variables declaration//GEN-END:variables
}
